name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye-slim
    steps:
    - uses: actions/checkout@v3
    
    - name: Update APT cache
      run: apt update

    - name: Install deb build dependencies
      run: apt-get -y install make debhelper-compat dh-python python3-all 
    
    - name: Install python build dependencies
      run: make install_build_deps
      
    - name: Build 
      run:
        make
